# Generated by Django 6.1 on 2026-09-25 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarjeta Gráfica')),
                ('monitor', models.CharField(blank=True, max_length=100, null=True)),
                ('perifericos', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(help_text='Ejemplo: images/pc1.jpeg', max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computadores', to='tiendaApp.categoria')),
            ],
        ),
    ]
