# Generated by Django 6.1 on 2026-09-25 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Figura3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(help_text='Ejemplo: images/impresion1.jpeg', max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figuras', to='bodegaApp.material')),
            ],
        ),
    ]
